### ISSUE TITLE
error:No column updated

### ISSUE THREAD

**Issue by nonamexz** [GoDannyLai/binlog_rollback#1]
mysql版本:5.7.24
操作系统：centos7.5

/opt/binlog/binlog_rollback \
-m repl -w 2sql \
-sbin mysql-bin.000088 -spos 154 \
-ebin mysql-bin.000099 -epos 154 \
-H 127.0.0.1 -u username -p ****** \
-e -o /opt/binlog 

执行时报错：

time="2019-03-07_15:26:11" level=error errcode=2
Fail to generate update sql for zentao.zt_searchdict mysql-bin.000088 1992987-1993098 
        error: No column updated.  Generated sql: UPDATE `zentao`.`zt_searchdict`
ORIGINAL STACK TRACE:
github.com/dropbox/godropbox/database/sqlbuilder.(*updateStatementImpl).String
        E:/danny/src/go/src/github.com/dropbox/godropbox/database/sqlbuilder/statement.go:721 +0x6a5981
main.GenUpdateSqlsForOneRowsEvent
        E:/danny/src/go/src/binlog_rollback/sqlgen.go:437 +0x6c038b
main.GenForwardRollbackSqlFromBinEvent
        E:/danny/src/go/src/binlog_rollback/process_events.go:367 +0x6b9f27
runtime.goexit
        D:/dannyinstall/go/src/runtime/asm_amd64.s:1333 +0x456481

        rows data:[-28691 迭]
[-28691 迭]

该段binlog内容如下：
mysqlbinlog  -vv --base64-output=DECODE-ROWS --start-position=1992987 --stop-position=1993098 mysql-bin.000088
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=1*/;
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
DELIMITER /*!*/;
# at 1992987
#190226  9:05:45 server id 101  end_log_pos 1993048 CRC32 0x49b86b7e 	Table_map: `zentao`.`zt_searchdict` mapped to number 2023
# at 1993048
#190226  9:05:45 server id 101  end_log_pos 1993098 CRC32 0x590d8ae5 	Update_rows: table id 2023 flags: STMT_END_F
###   @2='迭' /* STRING(9) meta=65033 nullable=0 is_null=0 */
SET @@SESSION.GTID_NEXT= 'AUTOMATIC' /* added by mysqlbinlog */ /*!*/;
DELIMITER ;
# End of log file
/*!50003 SET COMPLETION_TYPE=@OLD_COMPLETION_TYPE*/;
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=0*/;

出错部分的数据库信息：
mysql> desc zt_searchdict;
+-------+----------------------+------+-----+---------+-------+
| Field | Type                 | Null | Key | Default | Extra |
+-------+----------------------+------+-----+---------+-------+
| key   | smallint(5) unsigned | NO   | PRI | NULL    |       |
| value | char(3)              | NO   |     | NULL    |       |
+-------+----------------------+------+-----+---------+-------+
2 rows in set (0.00 sec)
mysql> select * from zt_searchdict where value="迭";
+-------+-------+
| key   | value |
+-------+-------+
| 36845 | 迭    |
+-------+-------+
1 row in set (0.00 sec)

**Comment by GoDannyLai** [comment]
加个参数-a会没这个错误， 但是很奇怪， 这个update前后数据是一样的， 也就是实际没有更新数据，应该不会出现在binlog中才对。
